/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.graphhopper.routeopt.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Activity
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-31T10:35:10.244+02:00")
public class Activity   {
  /**
   * type of activity
   */
  public enum TypeEnum {
    @SerializedName("start")
    START("start"),
    
    @SerializedName("end")
    END("end"),
    
    @SerializedName("service")
    SERVICE("service"),
    
    @SerializedName("pickupShipment")
    PICKUPSHIPMENT("pickupShipment"),
    
    @SerializedName("deliverShipment")
    DELIVERSHIPMENT("deliverShipment");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("location_id")
  private String locationId = null;

  @SerializedName("arr_time")
  private Long arrTime = null;

  @SerializedName("end_time")
  private Long endTime = null;

  public Activity type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * type of activity
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "type of activity")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public Activity id(String id) {
    this.id = id;
    return this;
  }

   /**
   * id referring to the underlying service or shipment, i.e. the shipment or service this activity belongs to
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "id referring to the underlying service or shipment, i.e. the shipment or service this activity belongs to")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Activity locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * id that refers to address
   * @return locationId
  **/
  @ApiModelProperty(example = "null", value = "id that refers to address")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public Activity arrTime(Long arrTime) {
    this.arrTime = arrTime;
    return this;
  }

   /**
   * arrival time at this activity in ms
   * @return arrTime
  **/
  @ApiModelProperty(example = "null", value = "arrival time at this activity in ms")
  public Long getArrTime() {
    return arrTime;
  }

  public void setArrTime(Long arrTime) {
    this.arrTime = arrTime;
  }

  public Activity endTime(Long endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * end time of and thus departure time at this activity
   * @return endTime
  **/
  @ApiModelProperty(example = "null", value = "end time of and thus departure time at this activity")
  public Long getEndTime() {
    return endTime;
  }

  public void setEndTime(Long endTime) {
    this.endTime = endTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Activity activity = (Activity) o;
    return Objects.equals(this.type, activity.type) &&
        Objects.equals(this.id, activity.id) &&
        Objects.equals(this.locationId, activity.locationId) &&
        Objects.equals(this.arrTime, activity.arrTime) &&
        Objects.equals(this.endTime, activity.endTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, id, locationId, arrTime, endTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Activity {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    arrTime: ").append(toIndentedString(arrTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

