/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.graphhopper.routeopt.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * CostMatrix
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-31T10:35:10.244+02:00")
public class CostMatrix   {
  /**
   * type of cost matrix, currently default or google are supported
   */
  public enum TypeEnum {
    @SerializedName("default")
    DEFAULT("default"),
    
    @SerializedName("google")
    GOOGLE("google");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("profile")
  private String profile = null;

  public CostMatrix type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * type of cost matrix, currently default or google are supported
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "type of cost matrix, currently default or google are supported")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public CostMatrix url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL of matrix service
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "URL of matrix service")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public CostMatrix profile(String profile) {
    this.profile = profile;
    return this;
  }

   /**
   * vehicle profile or empty if catch all fallback
   * @return profile
  **/
  @ApiModelProperty(example = "null", value = "vehicle profile or empty if catch all fallback")
  public String getProfile() {
    return profile;
  }

  public void setProfile(String profile) {
    this.profile = profile;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CostMatrix costMatrix = (CostMatrix) o;
    return Objects.equals(this.type, costMatrix.type) &&
        Objects.equals(this.url, costMatrix.url) &&
        Objects.equals(this.profile, costMatrix.profile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, url, profile);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CostMatrix {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

