/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.graphhopper.routeopt.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * Relation
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-22T09:15:07.913+02:00")
public class Relation   {
  @SerializedName("type")
  private String type = null;

  @SerializedName("ids")
  private List<String> ids = new ArrayList<String>();

  @SerializedName("vehicle_id")
  private String vehicleId = null;

  public Relation type(String type) {
    this.type = type;
    return this;
  }

   /**
   * identifier of relation
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "identifier of relation")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Relation ids(List<String> ids) {
    this.ids = ids;
    return this;
  }

  public Relation addIdsItem(String idsItem) {
    this.ids.add(idsItem);
    return this;
  }

   /**
   * An array of ids that should be related
   * @return ids
  **/
  @ApiModelProperty(example = "null", value = "An array of ids that should be related")
  public List<String> getIds() {
    return ids;
  }

  public void setIds(List<String> ids) {
    this.ids = ids;
  }

  public Relation vehicleId(String vehicleId) {
    this.vehicleId = vehicleId;
    return this;
  }

   /**
   * vehicle id
   * @return vehicleId
  **/
  @ApiModelProperty(example = "null", value = "vehicle id")
  public String getVehicleId() {
    return vehicleId;
  }

  public void setVehicleId(String vehicleId) {
    this.vehicleId = vehicleId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Relation relation = (Relation) o;
    return Objects.equals(this.type, relation.type) &&
        Objects.equals(this.ids, relation.ids) &&
        Objects.equals(this.vehicleId, relation.vehicleId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, ids, vehicleId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Relation {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    ids: ").append(toIndentedString(ids)).append("\n");
    sb.append("    vehicleId: ").append(toIndentedString(vehicleId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

