/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.graphhopper.routeopt.client.api;

import com.graphhopper.routeopt.client.ApiException;
import com.graphhopper.routeopt.client.model.Response;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SolutionApi
 */
public class SolutionApiTest {

    private final SolutionApi api = new SolutionApi();

    
    /**
     * Return the solution associated to the jobId
     *
     * This endpoint returns the solution of a large problems. You can fetch it with the job_id, you have been sent. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSolutionTest() throws ApiException {
        String key = null;
        String jobId = null;
        // Response response = api.getSolution(key, jobId);

        // TODO: test validations
    }
    
}
