/**
 * Route Optimization API
 * Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.graphhopper.routeopt.client.api;

import com.graphhopper.routeopt.client.ApiException;
import com.graphhopper.routeopt.client.model.JobId;
import com.graphhopper.routeopt.client.model.Request;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VrpApi
 */
public class VrpApiTest {

    private final VrpApi api = new VrpApi();

    
    /**
     * Solves vehicle routing problems
     *
     * This endpoint for solving vehicle routing problems, i.e. traveling salesman or vehicle routing problems, and returns the solution. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postVrpTest() throws ApiException {
        String key = null;
        Request body = null;
        // JobId response = api.postVrp(key, body);

        // TODO: test validations
    }
    
}
